### ISSUE TITLE
Sonoff 4CH Pro: Looking for GPIO 1-3 Pin location

### ISSUE THREAD

**Issue by aherzer69** [qtoggle/espqtoggle#56]
Hello,
I am looking for the GPIO pins 1-3 on the Sonoff 4CH pro (just found GPIO 0 pin for flashing).
Could anybody please upload a picture with the location?
I would like to install a temp. sensor.
Thank you in advanced & best regards Axel

**Comment by ccrisan** [comment]
@aherzer69 if your're really looking for GPIO1 and GPIO3 pins of the ESP chip, they are in fact the TX and RX connectors:

![](https://raw.githubusercontent.com/wiki/qtoggle/espqtoggle/images/devices/sonoff-4ch/sonoff-4ch-boards.jpg)

However that's a odd choice for installing a temperature sensor. Also keep in mind that 4CH Pro does this weird thing of passing all button inputs and relay outputs through another microcontroller, instead of having them connected directly. This may pose problems in some cases.

**Comment by aherzer69** [comment]
Thank you for the fast response ccrisan! That is exactly answeríng my question. 
I also found GPIO2 (=SDO).
![image](https://user-images.githubusercontent.com/41234826/79912705-bc3b9f80-8422-11ea-9276-35ebdc67f9ac.png)
